In [191]:
import numpy as np
import pandas as pd
import sklearn

In [192]:
df=pd.read_csv("/Users/jammasangeetha13gmail.com/Downloads/student_dataset_10000_rows.csv")
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [237]:
X = df.drop(["exam_score", "placement_status"], axis=1)
y = df[["exam_score"]]

In [238]:
y

      exam_score
0         100.00
1         100.00
2         100.00
3          90.17
4          78.82
...          ...
9995       69.31
9996      100.00
9997       95.94
9998       88.61
9999       78.96

[10000 rows x 1 columns]

In [239]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [268]:
num_df=X_train[['study_hours','attendance','sleep_hours','internet_usage','assignments_completed','previous_score']]
num_df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score
9254,11,58,5,7,5,70
1561,11,93,4,10,0,83
1670,7,86,7,5,14,85
6087,3,53,4,4,6,68
6669,10,98,4,4,8,57
...,...,...,...,...,...,...
5734,11,67,4,8,2,51
5191,7,96,9,7,6,86
5390,9,91,4,10,19,81
860,1,71,5,2,12,72
7270,1,79,9,2,6,37

In [269]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler().set_output(transform='pandas')
x_train_trans = scaler.fit_transform(num_df)

In [270]:
x_train_trans

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score
9254,1.0,0.300000,0.2,0.6,0.25,0.583333
1561,1.0,0.883333,0.0,0.9,0.00,0.800000
1670,0.6,0.766667,0.6,0.4,0.70,0.833333
6087,0.2,0.216667,0.0,0.3,0.30,0.550000
6669,0.9,0.966667,0.0,0.3,0.40,0.366667
...,...,...,...,...,...,...
5734,1.0,0.450000,0.0,0.7,0.10,0.266667
5191,0.6,0.933333,1.0,0.6,0.30,0.850000
5390,0.8,0.850000,0.0,0.9,0.95,0.766667
860,0.0,0.516667,0.2,0.1,0.60,0.616667
7270,0.0,0.650000,1.0,0.1,0.30,0.033333

In [271]:
x_train_trans.reset_index(inplace=True, drop=True)
x_train_trans

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score
0,1.0,0.300000,0.2,0.6,0.25,0.583333
1,1.0,0.883333,0.0,0.9,0.00,0.800000
2,0.6,0.766667,0.6,0.4,0.70,0.833333
3,0.2,0.216667,0.0,0.3,0.30,0.550000
4,0.9,0.966667,0.0,0.3,0.40,0.366667
...,...,...,...,...,...,...
7995,1.0,0.450000,0.0,0.7,0.10,0.266667
7996,0.6,0.933333,1.0,0.6,0.30,0.850000
7997,0.8,0.850000,0.0,0.9,0.95,0.766667
7998,0.0,0.516667,0.2,0.1,0.60,0.616667
7999,0.0,0.650000,1.0,0.1,0.30,0.033333

In [272]:
num_df_y.reset_index(drop=True,inplace=True)
num_df_y

      exam_score
0          94.33
1         100.00
2         100.00
3          50.01
4          98.32
...          ...
7995       74.49
7996      100.00
7997      100.00
7998       91.08
7999       61.26

[8000 rows x 1 columns]

In [273]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [274]:
X_test.reset_index(inplace=True, drop=True)
X_test

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score
0,8,94,4,6,18,76
1,6,99,5,6,2,78
2,8,86,5,6,6,62
3,1,54,9,7,6,92
4,10,88,6,9,10,39
...,...,...,...,...,...,...
1995,2,67,4,2,8,53
1996,10,70,9,8,4,43
1997,3,100,8,6,10,66
1998,9,90,9,3,12,60
1999,6,44,5,6,3,65

In [275]:
y_test.reset_index(inplace=True, drop=True)
y_test

      exam_score
0         100.00
1          84.07
2          95.37
3          83.96
4          78.58
...          ...
1995       69.44
1996      100.00
1997       96.35
1998      100.00
1999       69.79

[2000 rows x 1 columns]

In [276]:
num_df_test = X_test[['study_hours','attendance','sleep_hours','internet_usage','assignments_completed','previous_score']]
num_df_test

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score
0,8,94,4,6,18,76
1,6,99,5,6,2,78
2,8,86,5,6,6,62
3,1,54,9,7,6,92
4,10,88,6,9,10,39
...,...,...,...,...,...,...
1995,2,67,4,2,8,53
1996,10,70,9,8,4,43
1997,3,100,8,6,10,66
1998,9,90,9,3,12,60
1999,6,44,5,6,3,65

In [279]:
X_test_trans = scaler.transform(num_df_test)
X_test_trans

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score
0,0.7,0.900000,0.0,0.5,0.90,0.683333
1,0.5,0.983333,0.2,0.5,0.10,0.716667
2,0.7,0.766667,0.2,0.5,0.30,0.450000
3,0.0,0.233333,1.0,0.6,0.30,0.950000
4,0.9,0.800000,0.4,0.8,0.50,0.066667
...,...,...,...,...,...,...
1995,0.1,0.450000,0.0,0.1,0.40,0.300000
1996,0.9,0.500000,1.0,0.7,0.20,0.133333
1997,0.2,1.000000,0.8,0.5,0.50,0.516667
1998,0.8,0.833333,1.0,0.2,0.60,0.416667
1999,0.5,0.066667,0.2,0.5,0.15,0.500000

In [280]:
y_pred = model.predict(X_test_trans)
y_pred

array([[29.29959734],
       [28.26789585],
       [28.87994074],
       ...,
       [28.57643478],
       [30.69426536],
       [28.07949908]], shape=(2000, 1))

In [284]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)

print("MSE :", mse)

MSE : 3527.3266278466326