In [191]:
import numpy as np
import pandas as pd
import sklearn

In [192]:
df=pd.read_csv("/Users/jammasangeetha13gmail.com/Downloads/student_dataset_10000_rows.csv")
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [193]:
X = df.drop("placement_status", axis=1)
y = df[["placement_status"]]

In [194]:
y

     placement_status
0              Placed
1              Placed
2              Placed
3              Placed
4              Placed
...               ...
9995       Not Placed
9996           Placed
9997           Placed
9998           Placed
9999           Placed

[10000 rows x 1 columns]

In [195]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [196]:
num_df=X_train[['study_hours','attendance','sleep_hours','internet_usage','assignments_completed','previous_score','exam_score']]
num_df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
9254,11,58,5,7,5,70,94.33
1561,11,93,4,10,0,83,100.00
1670,7,86,7,5,14,85,100.00
6087,3,53,4,4,6,68,50.01
6669,10,98,4,4,8,57,98.32
...,...,...,...,...,...,...,...
5734,11,67,4,8,2,51,74.49
5191,7,96,9,7,6,86,100.00
5390,9,91,4,10,19,81,100.00
860,1,71,5,2,12,72,91.08
7270,1,79,9,2,6,37,61.26

In [197]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler().set_output(transform='pandas')
x_train_trans = scaler.fit_transform(num_df)

In [198]:
x_train_trans

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
9254,1.0,0.300000,0.2,0.6,0.25,0.583333,0.922678
1561,1.0,0.883333,0.0,0.9,0.00,0.800000,1.000000
1670,0.6,0.766667,0.6,0.4,0.70,0.833333,1.000000
6087,0.2,0.216667,0.0,0.3,0.30,0.550000,0.318287
6669,0.9,0.966667,0.0,0.3,0.40,0.366667,0.977090
...,...,...,...,...,...,...,...
5734,1.0,0.450000,0.0,0.7,0.10,0.266667,0.652121
5191,0.6,0.933333,1.0,0.6,0.30,0.850000,1.000000
5390,0.8,0.850000,0.0,0.9,0.95,0.766667,1.000000
860,0.0,0.516667,0.2,0.1,0.60,0.616667,0.878358
7270,0.0,0.650000,1.0,0.1,0.30,0.033333,0.471703

In [199]:
x_train_trans.reset_index(inplace=True, drop=True)
x_train_trans

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
0,1.0,0.300000,0.2,0.6,0.25,0.583333,0.922678
1,1.0,0.883333,0.0,0.9,0.00,0.800000,1.000000
2,0.6,0.766667,0.6,0.4,0.70,0.833333,1.000000
3,0.2,0.216667,0.0,0.3,0.30,0.550000,0.318287
4,0.9,0.966667,0.0,0.3,0.40,0.366667,0.977090
...,...,...,...,...,...,...,...
7995,1.0,0.450000,0.0,0.7,0.10,0.266667,0.652121
7996,0.6,0.933333,1.0,0.6,0.30,0.850000,1.000000
7997,0.8,0.850000,0.0,0.9,0.95,0.766667,1.000000
7998,0.0,0.516667,0.2,0.1,0.60,0.616667,0.878358
7999,0.0,0.650000,1.0,0.1,0.30,0.033333,0.471703

In [200]:
cat_df=y_train[["placement_status"]]
cat_df

     placement_status
9254           Placed
1561           Placed
1670           Placed
6087       Not Placed
6669           Placed
...               ...
5734           Placed
5191           Placed
5390           Placed
860            Placed
7270       Not Placed

[8000 rows x 1 columns]

In [201]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in cat_df:
    cat_df[col] = le.fit_transform(cat_df[col])

In [202]:
cat_df.reset_index(drop=True,inplace=True)
cat_df

      placement_status
0                    1
1                    1
2                    1
3                    0
4                    1
...                ...
7995                 1
7996                 1
7997                 1
7998                 1
7999                 0

[8000 rows x 1 columns]

In [207]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train_trans, y_train.values.ravel())

LogisticRegression()

In [208]:
X_test.reset_index(inplace=True, drop=True)
X_test

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
0,8,94,4,6,18,76,100.00
1,6,99,5,6,2,78,84.07
2,8,86,5,6,6,62,95.37
3,1,54,9,7,6,92,83.96
4,10,88,6,9,10,39,78.58
...,...,...,...,...,...,...,...
1995,2,67,4,2,8,53,69.44
1996,10,70,9,8,4,43,100.00
1997,3,100,8,6,10,66,96.35
1998,9,90,9,3,12,60,100.00
1999,6,44,5,6,3,65,69.79

In [209]:
y_test.reset_index(inplace=True, drop=True)
y_test

     placement_status
0              Placed
1              Placed
2              Placed
3              Placed
4              Placed
...               ...
1995       Not Placed
1996           Placed
1997           Placed
1998           Placed
1999       Not Placed

[2000 rows x 1 columns]

In [210]:
num_df_test = X_test[['study_hours',
                      'attendance',
                      'sleep_hours',
                      'internet_usage',
                      'assignments_completed',
                      'previous_score',
                      'exam_score']]
num_df_test

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
0,8,94,4,6,18,76,100.00
1,6,99,5,6,2,78,84.07
2,8,86,5,6,6,62,95.37
3,1,54,9,7,6,92,83.96
4,10,88,6,9,10,39,78.58
...,...,...,...,...,...,...,...
1995,2,67,4,2,8,53,69.44
1996,10,70,9,8,4,43,100.00
1997,3,100,8,6,10,66,96.35
1998,9,90,9,3,12,60,100.00
1999,6,44,5,6,3,65,69.79

In [211]:
X_test_trans = scaler.transform(num_df_test)
X_test_trans

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
0,0.7,0.900000,0.0,0.5,0.90,0.683333,1.000000
1,0.5,0.983333,0.2,0.5,0.10,0.716667,0.782763
2,0.7,0.766667,0.2,0.5,0.30,0.450000,0.936861
3,0.0,0.233333,1.0,0.6,0.30,0.950000,0.781263
4,0.9,0.800000,0.4,0.8,0.50,0.066667,0.707896
...,...,...,...,...,...,...,...
1995,0.1,0.450000,0.0,0.1,0.40,0.300000,0.583254
1996,0.9,0.500000,1.0,0.7,0.20,0.133333,1.000000
1997,0.2,1.000000,0.8,0.5,0.50,0.516667,0.950225
1998,0.8,0.833333,1.0,0.2,0.60,0.416667,1.000000
1999,0.5,0.066667,0.2,0.5,0.15,0.500000,0.588027

In [212]:
y_pred = model.predict(X_test_trans)
y_pred

array(['Placed', 'Placed', 'Placed', ..., 'Placed', 'Placed',
       'Not Placed'], shape=(2000,), dtype=object)

In [213]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.9835